openapi: "3.0.0"
info:
  version: 1.0.0
  title: Expressions
paths:
  /vars:
    get:
      summary: list available variables
      operationId: listVariables
      tags:
        - metaManagement
      responses:
        200:
          description: variables list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Variable"
  /vars/clean:
    delete:
      summary: remove all variables
      operationId: cleanVariables
      tags:
        - metaManagement
      responses:
        200:
          description: Deleted
  /expr:
    post:
      summary: calculate expression
      operationId: expressionCalc
      tags:
        - calculateExpressions
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InputExpression"
      responses:
        200:
          description: Inserted product info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OutputResult"
components:
  schemas:
    InputExpression:
      type: object
      properties:
        expression:
          type: string
          example: 2 + 3 * 4
          description: expression to be calculated
      required:
        - expression
    OutputResult:
      type: object
      properties:
        result:
          type: number
          format: double
          example: 1234
      required:
        - result
    Variable:
      type: object
      properties:
        name:
          type: string
          example: x
          description: variable`s name
        value:
          type: number
          format: double
          example: 0.5
          description: value assigned to variable
